---
title: "Article 5 : Microplastic Pollution Found in Snow in the Remotest Corners of the World "
description: | 
  Five article  : Researchers discovered microplastic pollutants in snow located in the Arctic and the Alps.
  
author:
  - name: Beaumariage Anaïs
    url: {}
date: 11-28-2019
categories: 
    - Microplastic
    - Pollution
    - Atmosphere
    
preview: imageintro5.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Source of the article with publication date and word count

*Source of the article* : [Interesting ingeneering](https://amp.interestingengineering.com/microplastic-pollution-found-in-snow-in-the-remotest-corners-of-the-world?fbclid=IwAR2BrdWO-8u270Y_DJlmE4D62FTyrOmNFEJ1iQw4lek5HkXlU7JUg7WgJFw) (August, 16, 2019)  
*Word count* : 579 words  

# Vocabulary  
| Word from the text    | Synonym/ definition    | French translation    |
| --- | --- | --- |
| to show up     | to come   | to arrive    |
| motion    | movement    | mouvement    |
| drifting ice floes    | floatting ice    | glaces flottantes    |
| rubber    | eraser    | gomme    |
| snowmobile    | car who ride in the ice    | motoneige    |
| tapping    | exploit    | exploiter    |
| dust    | dirt    | poussière    |
| tapping    | exploit    | exploiter    |


# Analysis table about the study
|     |     |
| --- | --- |
|  Researchers   |Donna Fuscaldo,  Alfred Wegener Institute and the Swiss WSL Institute for Snow and Avalanche Research,  Dr. Melanie Bergmann and Dr. Gunnar Gerdts  |
| Published in ? When ?    | in  Science Advances and in Interesting ingeneering on the 16th August 2019   |
| General topic    | The extend of microplastic in the environment    |
| Procedure/ what was examined    |  - Collecting samples of snow usaing a variety of methods   - Determine the type of microplastic by using a infrared spectroscopy   |
| Conclusion/discovery    | - High concentration of microplastic  animals, oceans, Artic, mountains, even in remote areas  - Microplastics in Arctic from nitrile rubber, acrylates and paint  - Highest concentration in rural road in Bavaria, followed by snow in Arctic  - Higher concentration in the snow than in dust deposits   |
| Remaining questions    |  Impact of microplastics on the environment and health of people ?  How much microplastics we're inhaling ?   |


