---
title: "Article 2 :'Biodegradable' plastic bags often don't break down"
description: |
  This is my second article. It's focussed on the degradation of plastic bags which means degradation in microplastics.
author:
  - name: Beaumariage Anaïs
date: 11-02-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Source of the article with publication date and word count

*Source of the article* : [Science news for students](https://www.sciencenewsforstudents.org/article/biodegradable-plastic-bags-often-dont-break-down) (June, 28, 2019)  
*Word count* : 873 words  

# Vocabulary  
| Word from the text    | Synonym/ definition    | French translation    |
| --- | --- | --- |
|trashed     | rubbished    | jeté    |
| litter    | rubbish    | ordure    |
| harm    | make pain    | nuire    |
| rot    | decay    | pourriture    |
| readily    | willingly    | volontiers    |
| claim    | demands    | revendication    |
| burry    | soak     |  tremper   |
| chunk    | piece    | morceau    |
| convenience    | ease    | commodité    |

# Analysis table about the study
|     |     |
| --- | --- |
|  Researchers   | Richard Thompson, Imon Napper   |
| Published in ? When ?    | in Environmental Science and Technology on the 7th May 2019 and in Sciences news for students on the 28th June 2019    |
| General topic    | Biodegradability of plastic bags    |
| Procedure/ what was examined    |  - Collecting 80 single-use plastic bags made of 4 types of biodegradable plastic  - Submerging them in ocean water, oil and placing them in the breeze, dark box during 3 years  - Measuring how well the plastic had broken down |
| Conclusion/discovery    | - Most of the bags unbroken   - In the air, broken in small pieces = Microplastic  - Object disappeared, material intact  - Microplastic eaten by microbes and animals or spread in the environment  - None of plastic bags broken in all the environment|
| Remaining questions    | Consequences for the environment ? How to use fewer plastics bags ? How to change our customs ? How to create better biodegradable plastic bags ?     |



