---
title: "My English activity log"
description: |
  This section is a summary of my English activity. That is to say : all things I've done in English and my link with this langage.
author:
  - name: Beaumariage Anaïs
    url: {}
date: 09-01-2019
categories: 
    
preview: imageintro3.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


I often watch videos in English on Youtube.  

I read articles on forums and socialnetworkingsites about travel, cooking, decoration,...  

I've read 3 books in English : "In the shadow of the mountain", "Detective work" and "A time to kill".  

I've watched several documents about Marylin Monroe in English. It was the subject of my essay in high school but I still enjoy watching films about her.  

I went to Greece this summer and I practised my English a lot. Last year, I won a contest from the European Commision to stimulate young people to move through Europe. My friend and I travelled during one week around Belgium, Netherlands, Dutchland, Czech republic and Austria. We communicated a lot in English and it's one of the most amazing trip in my life !  

I've two applications to improve my english on my phone : Duolingo and Memrise. I often do exercies on it.

I regulary watch videos on Youtube about Portugal : things to do, sightseeing, food, cultural activities because I'm travelling to Porto and Lisboa next July.

I watched somes films in English with english subtitles (Treasure Planet, 1917,...) and I started a serie : You. During this lockdown I try to get the best and to improve my English.  

I also watch sportvideo (training, stretching, workout, relaxation) in English on YouTube.
