---
title: "Article 1 : Microplastics are blowing in the wind"
description: |
  Here is my first analysis for my portfolio witch is focussed on microplastic pollution.
author:
  - name: Beaumariage Anaïs
date: 10-20-2019
categories: 
    - Microplastic
    - Pollution
preview: imageintro1.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Source of the article with publication date and word count

*Source of the article* : [Sciences news for students](https://www.sciencenewsforstudents.org/article/microplastics-are-blowing-wind) (May, 7, 2019)  
*Word count* : 726 words  

# Vocabulary  
| Word from the text    | Synonym/ definition    | French translation    |
| --- | --- | --- |
|remote     | isolated    | éloigné    |
| spot    | place    | endroit    |
| bits    | pieces    | morceaux    |
| trash    | rubbish    | déchets    |
| rival    | to be concurrent    | concurrencer    |
| set up    | configure    | mettre en place    |
| roughly    | approximately     |  à peu près   |
| tally    | match    | concorder    |
| fallout    | consequence    | retombée    |
| slender    | small    | minces    |
| shed    | get rid of    | se débarasser    |
| burst    | sudden rush    | rafale    |
| sample    | specimen    | échantillon    |  

# Analysis table about the study
|     |     |
| --- | --- |
|  Researchers   | Steve Allen ,Deonie Allen ,Vernon R. Phoenix ,Gaël Le Roux ,Pilar Durántez Jiménez ,Anaëlle Simonneau ,Stéphane Binet &Didier Galop    |
| Published in ? When ?    | Nature Geosciences on the 15th April 2019 and Sciences News for students on the 7th May 2019    |
| General topic    | Microplastic in the air in the French Pyrennes    |
| Procedure/ what was examined    |  - Collecting microplastic falling out of the air for five mounts  - Separate plastic bits  - Identified them by type, amount and origin    |
| Conclusion/discovery    | - Huge travel of microplastic in the wind  - Similar amount of microplastic in the air of Paris and in mountain  - Different types of microplastic: polypropylene or PET in Paris and polystyrene or polyethylene in the French Pyrennes    |
| Remaining questions    | Consequences for the environnement and humain health ?    |


